version: "3.9"
services:
  builder:
    build: .
    container_name: android-builder
    command: "bash"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./data:/AOSP